export const REQUEST_FETCH_SUCCESS = 'REQUEST_FETCH_SUCCESS';
export const CANDIDATE_LIST_FETCH_SUCCESS = 'CANDIDATE_LIST_FETCH_SUCCESS';
export const USER_LIST_FETCH_ALL_SUCCESS = 'USER_LIST_FETCH_ALL_SUCCESS';
export const CV_LIST_FETCH_SUCCESS = 'CV_LIST_FETCH_SUCCESS';
export const CANDIDATE_STATUS_FETCH_ALL = 'CANDIDATE_STATUS_FETCH_ALL';
export const CANDIDATE_LOGS_FETCH_ALL = 'CANDIDATE_LOGS_FETCH_ALL';
export const CANDIDATE_INTERVIEWS_FETCH_ALL = 'CANDIDATE_INTERVIEWS_FETCH_ALL';
export const INTERVIEW_UPDATE = 'INTERVIEW_UPDATE';
export const COMMENT_LIST_UPDATE = 'COMMENT_LIST_UPDATE';
export const CANDIDATE_UPDATE = 'CANDIDATE_UPDATE';
export const CV_UPDATE = 'CV_UPDATE';
export const DOMAIN_STORE_UPDATE = 'DOMAIN_STORE_UPDATE';

