export const REQUEST_SELECT = 'REQUEST_SELECT';
export const REQUEST_ASSIGNEE_SELECT = 'REQUEST_ASSIGNEE_SELECT';
export const FILTER_CANDIDATES = 'FILTER_CANDIDATES';
export const CURRENT_CANDIDATE_CHANGE = 'CURRENT_CANDIDATE_CHANGE';
export const CURRENT_CANDIDATE_RESET = 'CURRENT_CANDIDATE_RESET';
export const CANDIDATE_SELECT = 'CANDIDATE_SELECT';
export const INTERVIEW_SELECT = 'INTERVIEW_SELECT';
export const SELECTED_CANDIDATES_RESET = 'SELECTED_CANDIDATES_RESET';
