export const CANDIDATE_TAB_SELECT = 'CANDIDATE_TAB_SELECT';
export const CANDIDATE_STATUS_CHANGE = 'CANDIDATE_STATUS_CHANGE';
export const INTERVIEW_TAB_SELECT = 'INTERVIEW_TAB_SELECT';
export const MODAL_OPEN = 'MODAL_OPEN';
